import React from 'react'
import '../styles/globals.css'
import Head from 'next/head'


function MyApp({ Component, pageProps }) {
  
  return (
    <div className='root-app'>
       <Head>
        <title>NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/css/globals.css" />
      </Head>
      
      <Component {...pageProps} />
    </div>
  )
  
}

export default MyApp
